#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$" --exclude-dir=vendor)

if [[ "$STAGED_GO_FILES" = "" ]]; then
 exit 0
fi

for FILE in $STAGED_GO_FILES
do
 gofumpt -w -s $FILE
done

exit 0